# Generated by Django 6.0.6 on 2026-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('RFQ_TRACKER', 'RFQ Tracker'), ('SALES_REP', 'Sales Rep')], default='RFQ_TRACKER', max_length=50),
        ),
    ]
