# Generated by Django 6.0.6 on 2026-07-07 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_division_fg_mail_rfq_sbu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('rfq_date', models.DateField()),
                ('rfq_no', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('rfq_due_date', models.DateField()),
                ('rfq_due_time', models.TimeField()),
                ('rfq_assign_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.customer')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.division')),
                ('fg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.fg')),
                ('rfq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.rfq')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('sbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.sbu')),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
        migrations.CreateModel(
            name='EnquiryFGDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_part_no', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('qty', models.IntegerField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_details', to='core.enquiry')),
            ],
            options={
                'db_table': 'enquiry_fg_details',
            },
        ),
    ]
