# Generated by Django 6.0.6 on 2026-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enquiry_enquiryfgdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='clarification_from_cs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='clarification_to_cs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ed_of_costing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ed_of_engg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ed_of_sales',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
