# Generated by Django 6.0.6 on 2026-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enquiry_clarification_from_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='actual_date_of_engg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='engg_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='Pending with Engg', max_length=50),
        ),
    ]
