# Generated by Django 6.0.6 on 2026-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enquiry_actual_date_of_engg_enquiry_engg_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='actual_date_of_costing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='costing_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
