# Generated by Django 6.0.6 on 2026-07-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_created_at_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_joined_idx',
        ),
    ]
