# Generated by Django 6.0.6 on 2026-07-10 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enquiry_lost_value_enquiry_open_l1_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='project_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='rfq_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(db_index=True, default='Pending with Engg', max_length=50),
        ),
        migrations.CreateModel(
            name='EnquiryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.enquiry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enquiry_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
