# Generated by Django 6.0.6 on 2026-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_enquiry_project_name_alter_enquiry_rfq_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='po_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/po/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='rfq_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/rfq/'),
        ),
    ]
