# Generated by Django 6.0.6 on 2026-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_enquiry_po_document_enquiry_rfq_document'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('quote_value__gte', 0)), name='check_quote_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('open_l1_value__gte', 0)), name='check_open_l1_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('lost_value__gte', 0)), name='check_lost_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('po_value__gte', 0)), name='check_po_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiryfgdetail',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='check_fg_qty_non_negative'),
        ),
    ]
