# Generated by Django 6.0.6 on 2026-07-10 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_enquiry_check_quote_value_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('NOTE', 'Note'), ('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('SYSTEM', 'System Event')], default='NOTE', max_length=20)),
                ('description', models.TextField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.enquiry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enquiry_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
