# Generated by Django 6.0.7 on 2026-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_create_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_aging',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quote_submission_aging',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending with Engg', 'Pending with Engineering'), ('Pending with Costing', 'Pending with Costing'), ('Sales to Quote', 'Sales to Quote'), ('Pending with Sales', 'Pending with Sales'), ('Quote Submitted', 'Quote Submitted'), ('On Hold', 'On Hold'), ('Open - L1', 'Open - L1'), ('Won', 'Won'), ('Lost', 'Lost'), ('Regretted', 'Regretted'), ('Quote Regretted', 'Quote Regretted')], db_index=True, default='Pending with Engg', max_length=50),
        ),
    ]
