# Generated by Django 6.0.7 on 2026-07-17 09:54

from django.db import migrations

def populate_aging_fields(apps, schema_editor):
    Enquiry = apps.get_model('core', 'Enquiry')
    for enquiry in Enquiry.objects.all():
        updated = False
        if enquiry.quote_date and enquiry.rfq_date:
            delta = enquiry.quote_date - enquiry.rfq_date
            enquiry.enquiry_aging = max(delta.days, 0)
            updated = True
            
        if enquiry.actual_date_of_sales and enquiry.quote_date:
            delta = enquiry.actual_date_of_sales - enquiry.quote_date
            enquiry.quote_submission_aging = max(delta.days, 0)
            updated = True
            
        if updated:
            enquiry.save(update_fields=['enquiry_aging', 'quote_submission_aging'])

def reverse_populate_aging_fields(apps, schema_editor):
    Enquiry = apps.get_model('core', 'Enquiry')
    Enquiry.objects.all().update(enquiry_aging=None, quote_submission_aging=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_rfq_aging_fields'),
    ]

    operations = [
        migrations.RunPython(populate_aging_fields, reverse_populate_aging_fields),
    ]
