# Generated by Django 6.0.7 on 2026-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_populate_aging_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enquiry',
            name='check_quote_value_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='enquiry',
            name='check_open_l1_value_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='enquiry',
            name='check_lost_value_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='enquiry',
            name='check_po_value_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_created_at_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_rfq_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_rfq_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enq_quote_date_idx',
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', 'sales_rep', 'rfq_date'], name='core_enquir_status_b0cce9_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['sales_rep', 'rfq_date'], name='core_enquir_sales_r_c2f71b_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', 'customer', 'rfq_date'], name='core_enquir_status_8bddb1_idx'),
        ),
        migrations.AlterModelTable(
            name='enquiry',
            table=None,
        ),
    ]
