# Generated by Django 6.0.7 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_enquiry_check_quote_value_non_negative_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='enq_stat_rep_date_idx',
            old_name='core_enquir_status_b0cce9_idx',
        ),
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='enq_rep_date_idx',
            old_name='core_enquir_sales_r_c2f71b_idx',
        ),
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='enq_stat_cust_date_idx',
            old_name='core_enquir_status_8bddb1_idx',
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['-created_at'], name='enq_created_at_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', '-created_at'], name='enq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['rfq_date'], name='enq_rfq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['rfq_due_date'], name='enq_rfq_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['quote_date'], name='enq_quote_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', 'rfq_due_date'], name='enq_stat_duedate_idx'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('quote_value__gte', 0)), name='check_quote_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('open_l1_value__gte', 0)), name='check_open_l1_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('lost_value__gte', 0)), name='check_lost_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('po_value__gte', 0)), name='check_po_value_non_negative'),
        ),
        migrations.AlterModelTable(
            name='enquiry',
            table='enquiries',
        ),
    ]
